name: Development Workflow

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches:
      - main

jobs:
  testing:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Set GOBIN
        run: go env -w GOBIN=/usr/local/bin
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
      - name: Tests
        run: go test -v